spring:
  application:
    name: routinemanager

  datasource:
    url: jdbc:postgresql://localhost:5469/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  ai:
    vertex:
      ai:
        gemini:
          api-key: ${GEMINI_API_KEY:your_google_ai_studio_api_key_here}